name: ase-project

services:
  db:
    container_name: movie-db
    image: postgres:16-alpine
    ports:
      - 5432:5432
    restart: unless-stopped
    env_file: .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "sh -c 'pg_isready -U ${DB_USER} -d ${DB_NAME}'",
        ]
      interval: 5s
      timeout: 10s
      retries: 6
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  api:
    container_name: movie-api
    build:
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 3001:3000
    env_file: .env
    environment:
      DB_HOST: db
      PORT: 3000
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://api:$PORT/api/healthy" ]
      interval: 5s
      timeout: 10s
      retries: 6
    volumes:
      - ./app:/app
      - /app/node_modules

volumes:
  db_data:
