name: ase-project

services:
  db:
    container_name: movie-db
    image: postgres:16-alpine
    ports:
      - 5432:5432
    restart: unless-stopped
    env_file: .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'",
        ]
      interval: 5s
      timeout: 10s
      retries: 6
    volumes:
      - db_data:/var/lib/postgresql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  api:
    container_name: movie-api
    build:
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 3001:3000
    env_file: .env
    environment:
      DB_HOST: db
      PORT: 3000
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:$PORT/api/health" ]
      interval: 5s
      timeout: 10s
      retries: 6
    volumes:
      - ./app:/app
      - /app/node_modules

  recommendation-service:
    container_name: recommender-service
    build:
      dockerfile: Dockerfile.recommender
    depends_on:
      db:
        condition: service_healthy
      api:
        condition: service_healthy
    ports:
      - 8001:8000
    env_file: .env
    environment:
      DB_HOST: db
      PORT: 8000
      EXPRESS_URL: http://api:3000
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:8000/health" ]
      interval: 5s
      timeout: 10s
      retries: 6
    volumes:
      - ./app/recommender-service:/app

volumes:
  db_data:
